# Kickstart container config file - see https://nfra.infracamp.org
# Run kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.1"

packages: [php8.1-curl, php8.1-http, php8.1-raphf, php8.1-mbstring, certbot]

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"

  test:
    - "/opt/vendor/bin/ptest"

  run:
    - "php -f bin/cert-issuer.php"
