# Kickstart container config file - see https://nfra.infracamp.org
# Run kickstart.sh to start a development-container for this project
version: 1
from: "nfra/kickstart-flavor-php:unstable"

packages: [php8.0-curl, php8.0-http, php8.0-raphf, php8.0-mbstring]

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"

  test:
    - "/opt/vendor/bin/ptest"

  run:
    - "curl http://localhost/hooks/repo"

